### ISSUE TITLE
Models Default to Vanilla

### ISSUE THREAD

**Issue by FreeMarcher** [cybercat5555/BetterAnimals#22] opened 2020-02-19 20:39 UTC
The mod seems to work fine with only three or four other mods installed, and I'm not really able to determine which mods are conflicting afterwards. It's almost like the models aren't rendering based on the amount of mods, alone. I don't know if that's possible, though.

ambient sounds 3
apple skin
aquaculture
attribute fix
better animal models
better animals plus
carpet stairs mod
carry on
configurable cane
corpse
customized dungeon loot
decorative blocks 3
dungeon crawl
equipment tooltips
extended caves
forbidden arcanus
grindstone sharper tools
guard villagers
gui clock
gui compass
hardcore revival
infernal mobs
metals, mining, and melting
minecraft boom
move plus
optifine
overloaded armor bar
paraglider
pick up notiofier
ping
randomium
recycler
scaling health
serene seasons
silent lib
simply tea
swing through grass
trajectory preview
tumbleweed
upgrade aquatic
valhelsia structures
water erosion
waddles
waystones

I tested it with everything both on and off, then again doing it all one at a time, and it works/doesn't work at seemingly random times. Now, with the entire load order, it very seldom works.

**Comment by itsmeow** [comment] 2020-02-20 06:39
I couldn't tell ya

**Comment by itsmeow** [comment] 2020-02-27 00:31
a couple of people have noted this with the newest version, could you try downgrading maybe?

**Comment by Areolata7** [comment] 2020-03-22 21:36
I was just going to report the same issue. I will also try to revert to the older file for now. 

The new file loads by forge without issue but 2 out of 3 loads the better animal models are not actually applied in game. So I have to quit and reload a few times for the mod to function. I installed the most recent file 1.14.4-5.3.0 at the time of release (mid-Feb) but this only started to happen recently. So it was fine for at least two weeks and now is breaking. I have not changed my forge version during this time but the MC launcher did do a seemingly large update on me recently. Could it be a conflict with the Mojang launcher?

If it is of any use the only mods I run in common with FreeMarcher are:

- ambient sounds 3
- aquaculture
- better animal models
- better animals plus
- corpse
- dungeon crawl
- extended caves
- optifine
- simply tea
- water erosion
- waddles

**Comment by Spectre93** [comment] 2020-03-29 08:36
I've been having the issue that only some animals rendered as new, but some used the default model. Installing the Quark mod seems to make all animals render as new for me, can you see if it works for you as well?

**Comment by itsmeow** [comment] 2020-04-01 04:04
I know what causes this, and it will be fixed when I get around to updating.

**Comment by itsmeow** [comment] 2020-04-13 16:07
Yes installing Quark fixes this issue. I didn't find it originally because the dev environment has Quark all the time, so when I was adding Quark compatibility I broke some of the default stuff.

**Comment by itsmeow** [comment] 2020-06-27 23:04
So it turns out what I thought fixed it.. doesn't and then I found another thing I think fixes it so. We'll see

**Comment by itsmeow** [comment] 2020-06-27 23:05
What MC version was this happening on?

**Comment by Spectre93** [comment] 2020-06-28 09:25
> What MC version was this happening on?

I believe it was 1.14.4

**Comment by FreeMarcher** [comment] 2020-06-28 15:24
1.14.4

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Areolata7** [comment] 2020-06-29 14:25
1.14.4 I just wanted to let you know that I have not had this issue for quite some time because I reverted and still run the older version 5.2.1 which works perfectly. I believe I was running forge 28.1.56 back in Feb. but I have been running 28.2.0 for some time now. I will go ahead and try the newest iteration again and report back the results. 

Update: I just tried version 5.3.0 again and same results as I reported before. First two loads of the game failed: the models were not applied. Third load it worked correctly. In these attempts I was near pigs, cows, chickens and sheep so I was unable to check cats, foxes, squid, etc. In February I had viewed some of the other creatures and the results were the same. So I do not have what others reported; where some animals are changed and others are not.  I have an all-or-none situation where it works completely but only every 3rd load.

**Comment by itsmeow** [comment] 2020-06-30 09:10
Can you test it with this beta? https://github.com/itsmeow/BetterAnimals/releases/tag/alpha-1.14.4-5.3.0.6

**Comment by Areolata7** [comment] 2020-06-30 14:03
Perfect!  Loaded 5.3.0.6 three times and three times it was successful. Confirmed that sheep/pigs/cows/chickens were all the new models. I was also able to check foxes and they were also correct. So this new beta is working for me and this is on a profile with 96 other mods (and no Quark).

**Closed as completed** 2020-11-28 04:53 UTC
Labels: bug
