### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Lordbaane** [cybercat5555/BetterAnimals#12] opened 2019-05-14 00:44 UTC
https://paste.dimdev.org/moqohiqawu.mccrash

**Comment by itsmeow** [comment] 2019-05-14 00:44
5.2 is alpha. Please revert while I fix this.

**Comment by itsmeow** [comment] 2019-05-14 15:03
Duplicate of #11. Releasing fix soon with 5.2.1

**Closed as completed by itsmeow** 2019-05-14 15:03 UTC
